### ISSUE TITLE
Tarefas 3

### ISSUE THREAD

**Issue by luiscsmuniz** [luiscsmuniz/Tasks#3]
- [x] comum: gettcomex/comum#78

- [x] comum: gettcomex/comum#70

- [x] comum: gettcomex/comum#71

- [x] comum: gettcomex/comum#31

- [x] comum: gettcomex/comum#28

- [x] comum: gettcomex/comum#24

- [x] comum: gettcomex/comum#72

- [x] comum: gettcomex/comum#73

- [x] comum: gettcomex/comum#74 skeleton

- [ ] arquivo: gettcomex/arquivo#90

- [ ] arquivo: gettcomex/arquivo#109

- [ ] arquivo: gettcomex/arquivo#110

- [x] arquivo: gettcomex/arquivo#86

- [x] arquivo: gettcomex/arquivo#84

- [x] arquivo: gettcomex/arquivo#112 skeleton

- [x] gateway: gettcomex/smarter-gateway#397

- [x] gateway: gettcomex/smarter-gateway#292 - fazer em paralelo (4h por semana)

- [ ] gateway: gettcomex/smarter-gateway#286 - fazer em paralelo (4h por semana)

- [x] gateway: gettcomex/smarter-gateway#399

- [x] gateway: gettcomex/smarter-gateway#394 - skeleton

- [x] template zendesk

- [ ] comercial: gettcomex/comercial#308
